import { bindChartTextGestures } from '../src/lib/chartTextGestures';

function check(condition: boolean, message: string) { if (!condition) throw new Error(message); }
const element = new EventTarget() as unknown as HTMLElement;
let size = 16;
let pinching = false;
let preview = 1;
const oldRequestFrame = globalThis.requestAnimationFrame;
const oldCancelFrame = globalThis.cancelAnimationFrame;
let pendingFrame: FrameRequestCallback | undefined;
globalThis.requestAnimationFrame = callback => { pendingFrame = callback; return 1; };
globalThis.cancelAnimationFrame = () => { pendingFrame = undefined; };
function frame() { const callback = pendingFrame; pendingFrame = undefined; callback?.(0); }
const dispose = bindChartTextGestures(element, { getSize: () => size, onPreview: value => { preview = value; }, onSize: value => { size = value; }, onPinching: value => { pinching = value; } });
function emit(type: string, properties: Record<string, unknown>) {
  const event = new Event(type, { cancelable: true });
  Object.assign(event, properties);
  element.dispatchEvent(event);
  return event;
}
const normal = emit('wheel', { altKey: false, deltaY: -80, deltaMode: 0 });
check(size === 16 && !normal.defaultPrevented, 'Normal scrolling must remain unchanged');
const wheel = emit('wheel', { altKey: true, deltaY: -80, deltaMode: 0 });
frame();
check(size === 16 && preview === 18 / 16 && wheel.defaultPrevented, 'Alt wheel previews without committing on every event');
await new Promise(resolve => setTimeout(resolve, 150));
check(size === 18, 'A wheel burst commits after settling');
emit('wheel', { altKey: true, ctrlKey: true, deltaY: -80, deltaMode: 0 });
check(size === 18, 'Do not intercept browser zoom modifiers');
const touches = (distance: number) => [{ clientX: 0, clientY: 0 }, { clientX: distance, clientY: 0 }];
emit('touchstart', { touches: touches(100) });
emit('touchmove', { touches: touches(150) });
frame();
check(size === 18 && preview === 1.5 && pinching, 'Pinch previews without expensive state updates');
emit('touchmove', { touches: touches(10) });
frame();
check(preview === 8 / 18, 'Preview respects minimum font size');
emit('touchmove', { touches: touches(400) });
frame();
check(preview === 2 && size === 18, 'Preview respects maximum without saving each move');
emit('touchend', { touches: [{ clientX: 0, clientY: 0 }] });
check(pinching && size === 18, 'One remaining finger keeps pinch ownership');
emit('touchcancel', {});
check(!pinching, 'Cancelled touch must release the pinch state');
emit('touchmove', { touches: touches(100) });
check(size === 36, 'Cancelled gestures must not continue changing text');
const single = emit('touchstart', { touches: [{ clientX: 0, clientY: 0 }] });
check(!single.defaultPrevented, 'One-finger scrolling must remain available');
size = 18;
emit('touchstart', { touches: touches(100) });
emit('touchmove', { touches: touches(101) });
emit('touchmove', { touches: touches(102) });
frame();
check(Math.abs(preview - 1.02) < 0.00001 && size === 18, 'Small pinch movements remain continuous below one font-size step');
emit('touchmove', { touches: touches(100) });
frame();
check(preview === 1, 'Returning to the original pinch distance resets the preview');
emit('touchend', { touches: [] });
check(size === 18 && !pinching, 'A no-change pinch releases cleanly');
dispose();
emit('wheel', { altKey: true, deltaY: 80, deltaMode: 0 });
check(size === 18, 'Unmount must remove input listeners');
globalThis.requestAnimationFrame = oldRequestFrame;
globalThis.cancelAnimationFrame = oldCancelFrame;
