import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { runInNewContext } from 'node:vm';
import ts from 'typescript';
let cleanup, timer, calls = [];
const listeners = new Map();
const doc = { visibilityState: 'hidden', addEventListener: (k,v) => listeners.set(k,v), removeEventListener: k => listeners.delete(k) };
const win = { setTimeout: fn => { timer=fn; return 1; }, clearTimeout: () => { timer=null; }, addEventListener: (k,v) => listeners.set(k,v), removeEventListener: k => listeners.delete(k) };
const exports = {};
const source = ts.transpileModule(await readFile(new URL('../src/components/EventUpdateViewTracker.tsx',import.meta.url),'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.React } }).outputText;
runInNewContext(source, { exports, window:win, document:doc, navigator:{onLine:true}, require: name => name==='react' ? { useEffect: fn => { cleanup=fn(); } } : { supabase:{rpc:(name,args) => { calls.push({name,args}); return Promise.resolve({data:true,error:null}); }} } });
exports.EventUpdateViewTracker({eventId:'event',rescheduledAt:'version'});
assert.equal(timer,null,'hidden tab must not record');
doc.visibilityState='visible'; listeners.get('visibilitychange')();
assert.equal(calls.length,0,'wait until visible event remains displayed');
timer(); await Promise.resolve();
assert.deepEqual(calls[0].args.p_event_id,'event');
assert.equal(calls[0].args.p_rescheduled_at,'version','pass version actually rendered');
listeners.get('visibilitychange')(); assert.equal(timer,null,'do not repeat successful view');
cleanup(); assert.equal(listeners.size,0,'navigation removes tracking listeners');
console.log('PASS event view tracker: visibility, delayed recording, rendered version, dedupe and cleanup');
