// Isolated database: no real members, telemetry, or backend mutations.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const db = new PGlite();
const orgA = '00000000-0000-4000-8000-000000000001';
const orgB = '00000000-0000-4000-8000-000000000002';
const admin = '00000000-0000-4000-8000-000000000011';
const member = '00000000-0000-4000-8000-000000000012';
const otherAdmin = '00000000-0000-4000-8000-000000000013';
const noOrg = '00000000-0000-4000-8000-000000000014';
try {
  await db.exec(`create role anon; create role authenticated; create role service_role;
    create schema auth;
    create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
    grant usage on schema auth to anon, authenticated;
    create table organizations(id uuid primary key);
    create table profiles(id uuid primary key, org_id uuid, is_org_admin boolean);
    create table native_push_devices(user_id uuid, org_id uuid);
    grant select on profiles to authenticated;
    insert into organizations values ('${orgA}'),('${orgB}');
    insert into profiles values ('${admin}','${orgA}',true),('${member}','${orgA}',false),('${otherAdmin}','${orgB}',true),('${noOrg}',null,false);`);
  const helpers = await readFile(new URL('../supabase/migrations/20260502000500_add_org_auth_helpers.sql', import.meta.url), 'utf8');
  await db.exec(helpers.slice(0, helpers.indexOf('create or replace function public.auth_is_org_leader')));
  await db.exec(await readFile(new URL('../supabase/migrations/20260923051442_member_app_access.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/20260923053629_android_app_recent_activity.sql', import.meta.url), 'utf8'));
  const as = async (role, user = '') => db.exec(`reset role; set role ${role}; set test.uid = '${user}';`);
  const record = (kind = 'browser', platform = 'other') => db.query('select record_member_app_access($1,$2)', [kind,platform]);
  const read = () => db.query('select * from member_app_access');
  await as('anon');
  await assert.rejects(record(), /permission denied/);
  await assert.rejects(read(), /permission denied/);
  await assert.rejects(db.query('select has_used_android_app()'), /permission denied/);
  await assert.rejects(db.query('select has_recent_android_app_activity()'), /permission denied/);
  await as('authenticated');
  await assert.rejects(record(), /Sign in/);
  await as('authenticated', noOrg);
  await assert.rejects(record(), /Organization/);
  await as('authenticated', member);
  assert.equal((await db.query('select has_used_android_app() as used')).rows[0].used, false);
  for (const args of [['invalid','other'],['android_app','ios'],['browser',null],[null,'other']]) await assert.rejects(record(...args), /Invalid/);
  await record();
  await record('pwa','android');
  await record('android_app','android');
  assert.equal((await db.query('select has_used_android_app() as used')).rows[0].used, true);
  assert.equal((await read()).rows.length, 0, 'ordinary members cannot inspect app access');
  await assert.rejects(db.exec(`insert into member_app_access values ('${admin}','${orgA}','browser','other',now())`), /permission denied/);
  await assert.rejects(db.exec('update member_app_access set last_seen_at = now()'), /permission denied/);
  await assert.rejects(db.exec('delete from member_app_access'), /permission denied/);
  await as('authenticated', admin);
  const rows = (await read()).rows;
  assert.equal(rows.length,3);
  assert.ok(rows.every(row => row.user_id === member && row.org_id === orgA), 'server derives identity');
  const first = rows.find(row => row.app_kind === 'browser').last_seen_at;
  await as('authenticated', member);
  await record();
  await as('authenticated', admin);
  assert.equal(String((await read()).rows.find(row=>row.app_kind==='browser').last_seen_at), String(first), 'repeat writes throttled on server');
  await as('authenticated', otherAdmin);
  assert.equal((await db.query('select has_used_android_app() as used')).rows[0].used, false, 'cannot infer someone else installed');
  assert.equal((await read()).rows.length,0,'another church admin cannot read records');
  await db.exec(`reset role; update member_app_access set last_seen_at=now()-interval '10 minutes' where app_kind='browser';`);
  await as('authenticated', member);
  await record();
  await as('authenticated', admin);
  assert.ok(new Date((await read()).rows.find(row=>row.app_kind==='browser').last_seen_at).getTime() >= new Date(first).getTime());
  await db.exec(`reset role; update profiles set org_id='${orgB}' where id='${member}';`);
  await as('authenticated', admin);
  assert.equal((await read()).rows.length,0,'previous church cannot inspect departed member');
  await as('authenticated', member);
  await record();
  await as('authenticated', otherAdmin);
  assert.equal((await read()).rows.length,1,'new church sees only newly observed access');
  await db.exec(`reset role; insert into native_push_devices values ('${otherAdmin}','${orgB}');`);
  await as('authenticated', otherAdmin);
  assert.equal((await db.query('select has_used_android_app() as used')).rows[0].used, true, 'existing push-enabled APK suppresses reminder too');
  const recent = async () => (await db.query('select has_recent_android_app_activity() as recent')).rows[0].recent;
  assert.equal(await recent(), false, 'old push registration alone must not pause reminders');
  await as('authenticated', member);
  assert.equal(await recent(), false, 'old church activity must not pause current church reminder');
  await record('android_app','android');
  assert.equal(await recent(), true, 'recent APK use pauses popup');
  await as('authenticated', otherAdmin);
  assert.equal(await recent(), false, 'another member activity must not pause caller reminder');
  await db.exec(`reset role; update member_app_access set last_seen_at=now()-interval '8 days' where user_id='${member}' and app_kind='android_app';`);
  await as('authenticated', member);
  assert.equal(await recent(), false, 'popup returns after seven days without use');
  await db.exec(`reset role; begin; update member_app_access set last_seen_at=now()-interval '7 days' where user_id='${member}' and app_kind='android_app';`);
  await as('authenticated', member);
  assert.equal(await recent(), false, 'exact seven-day boundary is expired');
  await db.exec('rollback');
  console.log('PASS app access DB: own recording, admin scope, tenant isolation, moved members, validation, throttling and denied direct writes');
} finally { await db.close(); }
