// Isolated PostgreSQL; no real recipients or push side effects.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const db = new PGlite();
const alice = '00000000-0000-4000-8000-000000000011';
const bob = '00000000-0000-4000-8000-000000000012';
const orgA = '00000000-0000-4000-8000-000000000001';
const orgB = '00000000-0000-4000-8000-000000000002';
const device = '00000000-0000-4000-8000-000000000021';
const secret = 'a'.repeat(64);
const token = 'test-device-token-'.repeat(3);
try {
  await db.exec(`create role anon; create role authenticated; create role service_role;
    create schema auth;
    create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
    grant usage on schema auth to anon, authenticated;
    create table public.organizations(id uuid primary key);
    create table public.profiles(id uuid primary key, org_id uuid);
    grant select on profiles to authenticated;
    insert into organizations values ('${orgA}'),('${orgB}');
    insert into profiles values ('${alice}','${orgA}'),('${bob}','${orgB}');`);
  await db.exec(await readFile(new URL('../supabase/migrations/20260923033724_android_native_push_devices.sql', import.meta.url), 'utf8'));
  const as = async (role, user = '') => db.exec(`reset role; set role ${role}; set test.uid = '${user}';`);
  const claim = (id = device, key = secret, value = token) => db.query('select claim_native_push_device($1,$2,$3)', [id, key, value]);
  const revoke = key => db.query('select revoke_native_push_device($1,$2)', [device, key]);
  await as('anon');
  await assert.rejects(claim(), /permission denied/);
  await as('authenticated', alice);
  await claim();
  assert.equal((await db.query('select enabled from native_push_devices')).rows[0].enabled, true);
  await assert.rejects(db.query('select token from native_push_devices'), /permission denied/);
  await assert.rejects(db.exec('delete from native_push_devices'), /permission denied/);
  await as('authenticated', bob);
  assert.equal((await db.query('select enabled from native_push_devices')).rows.length, 0, 'another church cannot see device');
  await assert.rejects(claim(device, 'b'.repeat(64)), /ownership/);
  await assert.rejects(claim('00000000-0000-4000-8000-000000000022'), /unique/);
  await claim(device, secret, 'new-token-'.repeat(5));
  assert.equal((await db.query('select user_id,org_id from native_push_devices')).rows[0].org_id, orgB, 'proven device follows authenticated church');
  await as('anon');
  await revoke('b'.repeat(64));
  await as('authenticated', bob);
  assert.equal((await db.query('select enabled from native_push_devices')).rows[0].enabled, true, 'wrong secret cannot revoke');
  await as('anon');
  await revoke(secret);
  await as('authenticated', bob);
  assert.equal((await db.query('select enabled from native_push_devices')).rows[0].enabled, false, 'expired session can securely revoke');
  await assert.rejects(claim(device, secret, 'bad'), /Invalid/);
  console.log('PASS native push database: RLS, grants, ownership, token collision, reassignment, revocation');
} finally { await db.close(); }
