import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const db = new PGlite();
const org = '00000000-0000-4000-8000-000000000001', otherOrg = '00000000-0000-4000-8000-000000000002';
const admin = '00000000-0000-4000-8000-000000000011', member = '00000000-0000-4000-8000-000000000012', outsider = '00000000-0000-4000-8000-000000000021';
const n1 = '00000000-0000-4000-8000-000000000031', n2 = '00000000-0000-4000-8000-000000000032', n3 = '00000000-0000-4000-8000-000000000033';
try {
  await db.exec(`create schema private; create schema auth; create role anon; create role authenticated;
    grant usage on schema auth to authenticated;
    create table organizations(id uuid primary key);
    create table profiles(id uuid primary key,org_id uuid,is_org_admin boolean);
    create table roles(id uuid primary key,name text);
    create table user_roles(user_id uuid,org_id uuid,role_id uuid);
    grant select on user_roles,roles to authenticated;
    create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
    create function public.auth_org_id() returns uuid language sql security definer set search_path='' as $$ select org_id from public.profiles where id=auth.uid() $$;
    create function public.auth_is_org_admin() returns boolean language sql security definer set search_path='' as $$ select is_org_admin from public.profiles where id=auth.uid() $$;
    create function public.is_platform_owner() returns boolean language sql as $$ select false $$;
    create table notifications(id uuid primary key,org_id uuid,user_id uuid,title text,body text,type text,
      data jsonb default '{}',created_at timestamptz default now(),push_status text default 'pending',is_read boolean default false);
    insert into organizations values ('${org}'),('${otherOrg}');
    insert into profiles values ('${admin}','${org}',true),('${member}','${org}',false),('${outsider}','${otherOrg}',true);
    insert into notifications(id,org_id,user_id,title,type) values (gen_random_uuid(),'${org}','${member}','Old alert','event_created');`);
  await db.exec(await readFile(new URL('../supabase/migrations/20260909065233_notification_open_activity.sql',import.meta.url),'utf8'));
  const rows = async query => (await db.query(query)).rows;
  assert.equal((await rows('select count(*) n from notification_activity'))[0].n,0,'no historical backfill');
  await db.exec(`insert into notifications(id,org_id,user_id,title,body,type) values
    ('${n1}','${org}','${admin}','Event reminder','Revamp tomorrow','event_reminder'),
    ('${n2}','${org}','${member}','Event reminder','Revamp tomorrow','event_reminder'),
    ('${n3}','${otherOrg}','${outsider}','Event reminder','Revamp tomorrow','event_reminder');
    insert into notifications(id,org_id,user_id,title,type) values(gen_random_uuid(),'${org}','${member}','Private chat','message');
    update notifications set is_read=true,push_status='sent' where id='${n2}';`);
  assert.equal((await rows('select count(*) n from notification_activity'))[0].n,3,'chat excluded');
  const before = (await rows(`select * from notification_activity where notification_id='${n2}'`))[0];
  assert.equal(before.is_read,true); assert.equal(before.bell_opened_at,null,'read is not an open');
  await db.exec(`set role authenticated; select set_config('test.uid','${member}',false)`);
  assert.equal((await rows('select count(*) n from notification_activity'))[0].n,0,'members cannot read activity');
  assert.equal((await rows("select count(*) n from get_notification_activity_groups()"))[0].n,0);
  const record = (id,source) => rows(`select record_notification_open('${id}','${source}') ok`);
  assert.equal((await record(n2,'bell'))[0].ok,true);
  assert.equal((await record(n1,'bell'))[0].ok,false,'cannot record another recipient');
  assert.equal((await record(n3,'push'))[0].ok,false,'cannot record another church');
  await assert.rejects(() => record(n2,'invalid'), /Invalid notification source/);
  await assert.rejects(() => db.exec(`update notification_activity set push_opened_at=now()`), /permission denied/);
  await record(n2,'bell'); await record(n2,'push');
  await db.exec(`select set_config('test.uid','${admin}',false)`);
  const groups = await rows('select * from get_notification_activity_groups()');
  assert.equal(groups.length,1,'same-batch matching alerts grouped, other church excluded');
  assert.equal(groups[0].recipient_count,2); assert.equal(groups[0].opened_count,1);
  assert.equal((await record(n2,'page'))[0].ok,false,'admins cannot forge another member open');
  const first = (await rows(`select bell_opened_at from notification_activity where notification_id='${n2}'`))[0].bell_opened_at;
  await db.exec(`select set_config('test.uid','${member}',false)`); await record(n2,'bell');
  await db.exec(`reset role; delete from notifications where id='${n2}';`);
  assert.equal((await rows(`select count(*) n from notification_activity where notification_id='${n2}'`))[0].n,1,'inbox clearing preserves the report');
  assert.equal((await rows(`select bell_opened_at from notification_activity where notification_id='${n2}'`))[0].bell_opened_at.toISOString(),first.toISOString(),'repeated taps preserve first timestamp');
  assert.equal((await rows("select has_function_privilege('anon','public.record_notification_open(uuid,text)','execute') ok"))[0].ok,false);
  assert.equal((await rows("select has_function_privilege('authenticated','private.record_notification_open(uuid,text)','execute') ok"))[0].ok,false);
  await db.exec(await readFile(new URL('../supabase/migrations/20260912073815_notification_activity_insights.sql',import.meta.url),'utf8'));
  await db.exec(`insert into notifications(id,org_id,user_id,title,type,push_status) values
    (gen_random_uuid(),'${org}','${member}','Failed alert','event_rescheduled','failed');
    insert into notifications(id,org_id,user_id,title,type,push_status,created_at) values
    (gen_random_uuid(),'${org}','${member}','Old alert','event_rescheduled','no_subscription',now()-interval '95 days');
    set role authenticated; select set_config('test.uid','${admin}',false);`);
  const insights = async (args = "now()-interval '30 days'") => (await rows(`select get_notification_activity_insights(${args}) result`))[0].result;
  const report = await insights();
  assert.equal(report.summary.notification_count,3,'full-period count excludes older and other-tenant records');
  assert.equal(report.summary.member_count,2,'distinct recipients across alerts');
  assert.equal(report.summary.opened_count,1,'multiple click sources count once');
  assert.equal(report.summary.accepted_count,1);
  assert.equal(report.summary.failed_count,1);
  assert.equal(report.summary.issue_count,1);
  assert.equal(report.summary.push_opened_count,1);
  assert.equal(report.summary.bell_opened_count,1);
  const issues = await insights("now()-interval '30 days',null,'issues'");
  assert.equal(issues.groups.length,1); assert.equal(issues.groups[0].title,'Failed alert');
  assert.equal(issues.summary.notification_count,3,'focus filter must not distort totals');
  const byType = await insights("now()-interval '30 days','event_reminder'");
  assert.equal(byType.summary.notification_count,2);
  const pageTwo = await insights("now()-interval '30 days',null,'all',25");
  assert.equal(pageTwo.groups.length,0); assert.equal(pageTwo.summary.notification_count,3);
  const detail = await insights(`now()-interval '30 days',null,'all',0,'${report.groups[0].group_id}'`);
  assert.equal(detail.summary.notification_count,report.groups[0].recipient_count);
  await db.exec(`select set_config('test.uid','${member}',false)`);
  assert.equal((await insights()).summary.notification_count,0,'member cannot access aggregate data');
  await db.exec(`select set_config('test.uid','${outsider}',false)`);
  assert.equal((await insights()).summary.notification_count,1,'other admin sees only own church');
  assert.equal((await rows("select has_function_privilege('anon','public.get_notification_activity_insights(timestamptz,text,text,integer,uuid)','execute') ok"))[0].ok,false);
  await db.exec(`reset role; alter table profiles add column first_name text; alter table profiles add column last_name text;
    update profiles set first_name='Test',last_name='Member' where id='${member}';
    update profiles set first_name='Test',last_name='Admin' where id='${admin}';
    grant select on profiles to authenticated;`);
  await db.exec(await readFile(new URL('../supabase/migrations/20260912074452_notification_activity_users.sql',import.meta.url),'utf8'));
  await db.exec(`set role authenticated; select set_config('test.uid','${admin}',false)`);
  const userReport = async (search='',offset=0) => (await rows(`select get_notification_activity_users(now()-interval '30 days','${search}',${offset}) result`))[0].result;
  const userList = await userReport();
  assert.equal(userList.total,2,'only own church users with activity');
  const memberStats = userList.users.find(u => u.user_id===member);
  assert.equal(memberStats.notification_count,2);
  assert.equal(memberStats.clicked_count,1,'multiple sources count once per recipient notification');
  assert.equal(memberStats.issue_count,1);
  assert.equal((await userReport('mEmBeR')).total,1,'case insensitive name search');
  assert.equal((await userReport('%')).total,0,'search is literal');
  assert.equal((await userReport('',25)).users.length,0);
  assert.equal((await userReport('',25)).total,2,'pagination retains full matching count');
  await db.exec(`select set_config('test.uid','${member}',false)`);
  assert.equal((await userReport()).total,0,'members cannot read user aggregates');
  await db.exec(`select set_config('test.uid','${outsider}',false)`);
  assert.equal((await userReport()).total,1,'other admin only sees own church');
  assert.equal((await rows("select has_function_privilege('anon','public.get_notification_activity_users(timestamptz,text,integer)','execute') ok"))[0].ok,false);
  await db.exec(`reset role;
    create table events(id uuid primary key,org_id uuid,rescheduled_at timestamptz);
    create table event_assignments(event_id uuid,user_id uuid,status text);
    grant select on events,event_assignments to authenticated;
    insert into events values('${n1}','${org}',null);
    insert into event_assignments values('${n1}','${member}','pending');
    update notifications set data=jsonb_build_object('event_id','${n1}'),type='event_invitation' where id='${n1}';`);
  await db.exec(await readFile(new URL('../supabase/migrations/20260912075705_event_notification_outcomes.sql',import.meta.url),'utf8'));
  await db.exec(`insert into notifications(id,org_id,user_id,title,type,data) values('${n2}','${org}','${member}','Invite','event_invitation',jsonb_build_object('event_id','${n1}'));`);
  // The earlier inbox-deletion fixture retains n2 in the audit, so create a fresh tracked invite.
  const fresh = '00000000-0000-4000-8000-000000000099';
  await db.exec(`insert into notifications(id,org_id,user_id,title,type,data) values('${fresh}','${org}','${member}','Invite','event_invitation',jsonb_build_object('event_id','${n1}'));
    set role authenticated; select set_config('test.uid','${outsider}',false);`);
  assert.equal((await rows(`select record_event_update_view('${n1}',null) ok`))[0].ok,false,'cross tenant view rejected');
  await db.exec(`select set_config('test.uid','${member}',false)`);
  assert.equal((await rows(`select record_event_update_view('${n1}',null) ok`))[0].ok,true,'direct event visit recorded');
  await db.exec(`select set_config('test.uid','${admin}',false)`);
  let outcome=(await rows(`select * from notification_activity_outcomes where notification_id='${fresh}'`))[0];
  assert.ok(outcome.event_viewed_at); assert.equal(outcome.bell_opened_at,null,'direct view does not invent click');
  assert.equal(outcome.response_status,'awaiting_response');
  await db.exec(`reset role; update event_assignments set status='confirmed' where event_id='${n1}';`);
  assert.equal((await rows(`select response_status from notification_activity_outcomes where notification_id='${fresh}'`))[0].response_status,'confirmed','response independent of clicks');
  await db.exec(`update events set rescheduled_at=now() where id='${n1}'; update event_assignments set status='pending' where event_id='${n1}';
    set role authenticated; select set_config('test.uid','${member}',false);`);
  assert.equal((await rows(`select record_event_update_view('${n1}',null) ok`))[0].ok,false,'stale rendered schedule rejected');
  await db.exec(`select set_config('test.uid','${admin}',false)`);
  assert.equal((await rows(`select response_status from notification_activity_outcomes where notification_id='${fresh}'`))[0].response_status,'superseded','old schedule excluded from followup');
  assert.equal((await rows(`select get_notification_activity_users(now()-interval '30 days') r`))[0].r.users.find(u=>u.user_id===member).needs_response_count,0);
  await db.exec(`select set_config('test.uid','${member}',false)`);
  assert.equal((await rows('select count(*) n from notification_activity_outcomes'))[0].n,0,'view preserves admin RLS');
  console.log('PASS notification activity DB: versioned direct views, stale schedule rejection, response outcomes, user counts and tenant RLS');
} catch(error) { console.error('FAIL notification activity DB:',error.message,error.where || ''); process.exitCode=1; }
finally { await db.close(); }
