import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const db = new PGlite();
const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const [org, otherOrg, manager, oldUser, newUser, outsider, event, role, assignment] = [1,2,3,4,5,6,7,8,9].map(uid);
const call = (target = assignment, replacement = newUser) => db.query('select public.replace_inactive_event_assignment($1,$2) as id', [target,replacement]);
const originalExists = async () => assert.equal((await db.query('select id from event_assignments where id=$1',[assignment])).rows.length,1);
try {
  await db.exec(`
    create role authenticated; create role anon; create schema auth;
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
    grant usage on schema auth to authenticated;
    create function public.auth_org_id() returns uuid language sql stable as $$select '${org}'::uuid$$;
    create function public.auth_is_org_leader() returns boolean language sql stable as $$select auth.uid()='${manager}'::uuid$$;
    create table profiles(id uuid primary key, org_id uuid, ministry_status text);
    create table events(id uuid primary key, org_id uuid, event_date date, start_time time, end_time time, lifecycle_override text);
    create table roles(id uuid primary key, name text);
    create table user_roles(org_id uuid, user_id uuid, role_id uuid);
    create table organization_member_settings(org_id uuid,user_id uuid,include_in_assignments boolean);
    create table user_availability(org_id uuid,user_id uuid,status text,request_type text,leave_type text,start_date date,end_date date,unavailable_date date);
    create table event_assignments(id uuid primary key default gen_random_uuid(), org_id uuid, event_id uuid references events, user_id uuid references profiles, role_id uuid references roles, status text, source_assignment_id uuid references event_assignments on delete cascade, unique(event_id,user_id,role_id));
    grant select,insert,update,delete on all tables in schema public to authenticated;
    alter table event_assignments enable row level security;
    create policy read_assignments on event_assignments for select to authenticated using(org_id=auth_org_id());
    create policy manage_assignments on event_assignments for all to authenticated using(org_id=auth_org_id() and auth_is_org_leader()) with check(org_id=auth_org_id() and auth_is_org_leader());
    insert into profiles values('${oldUser}','${org}','inactive'),('${newUser}','${org}','active'),('${outsider}','${otherOrg}','active');
    insert into events values('${event}','${org}','2099-01-01','09:00','11:00',null);
    insert into roles values('${role}','Song Leader');
    insert into user_roles values('${org}','${newUser}','${role}');
    insert into event_assignments(id,org_id,event_id,user_id,role_id,status) values('${assignment}','${org}','${event}','${oldUser}','${role}','pending');
    create function reject_test_insert() returns trigger language plpgsql as $$begin if current_setting('test.fail',true)='yes' then raise exception 'Simulated insert failure'; end if; return new; end$$;
    create trigger test_insert before insert on event_assignments for each row execute function reject_test_insert();
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/20261009093132_replace_inactive_event_assignment.sql',import.meta.url),'utf8'));
  await db.exec(`set role authenticated; set test.uid='${newUser}';`);
  await assert.rejects(call(), /leadership access/);
  await db.exec(`set test.uid='${manager}';`);
  await assert.rejects(call(uid(99)), /changed or is unavailable/);
  await assert.rejects(call(assignment,outsider), /active member from this church/);
  await assert.rejects(call(assignment,oldUser), /active member/);
  await db.exec(`update profiles set ministry_status='inactive' where id='${newUser}';`);
  await assert.rejects(call(), /active member/);
  await db.exec(`update profiles set ministry_status='active' where id='${newUser}'; insert into organization_member_settings values('${org}','${newUser}',false);`);
  await assert.rejects(call(), /excluded/);
  await db.exec(`delete from organization_member_settings; delete from user_roles;`);
  await assert.rejects(call(), /serves in this role/);
  await db.exec(`insert into user_roles values('${org}','${newUser}','${role}'); insert into user_availability(org_id,user_id,status,leave_type,unavailable_date) values('${org}','${newUser}','approved','single','2099-01-01');`);
  await assert.rejects(call(), /marked Out/);
  await db.exec(`delete from user_availability; update events set lifecycle_override='completed';`);
  await assert.rejects(call(), /Only upcoming/);
  await db.exec(`update events set lifecycle_override=null; update profiles set ministry_status='active' where id='${oldUser}';`);
  await assert.rejects(call(), /no longer needs/);
  await db.exec(`update profiles set ministry_status='inactive' where id='${oldUser}'; insert into event_assignments(org_id,event_id,user_id,role_id,status) values('${org}','${event}','${newUser}','${role}','pending');`);
  await assert.rejects(call(), /already assigned/);
  await db.exec(`delete from event_assignments where user_id='${newUser}'; insert into events values('${uid(20)}','${org}','2020-01-01','09:00','11:00',null); insert into event_assignments(id,org_id,event_id,user_id,role_id,status,source_assignment_id) values('${uid(21)}','${org}','${uid(20)}','${oldUser}','${role}','pending','${assignment}');`);
  await assert.rejects(call(), /past linked rehearsals/);
  await db.exec(`update events set event_date='2099-01-01' where id='${uid(20)}';`);
  await assert.rejects(call(uid(21)), /source service first/);
  await db.exec(`delete from event_assignments where id='${uid(21)}'; set test.fail='yes';`);
  await assert.rejects(call(), /Simulated insert failure/);
  await originalExists();
  await db.exec(`set test.fail='no';`);
  const replacementId = (await call()).rows[0].id;
  assert.equal((await db.query('select id from event_assignments where id=$1',[assignment])).rows.length,0);
  const replacement = (await db.query('select * from event_assignments where id=$1',[replacementId])).rows[0];
  assert.equal(replacement.user_id,newUser); assert.equal(replacement.role_id,role); assert.equal(replacement.status,'pending');
  await assert.rejects(call(), /changed or is unavailable/);
  await db.exec('reset role; set role anon;');
  await assert.rejects(call(), /permission denied/);
  console.log('PASS replacement: same-role pending assignment; insert failure rolls back deletion; role, church, status, availability, excluded member, completed event, stale assignment and anonymous boundaries');
} finally { await db.close(); }
